spring.profiles.active=dev
server.port=8090
server.servlet.context-path=/api

springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html
logging.pattern.console=%d{HH:mm:ss} [%level] %logger{36} - %msg%n

smartinventory.api.service-name=SmartInventory API
smartinventory.api.version=1.0.0
smartinventory.features.purchase-orders.enabled=true
